services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_farmacia
    ports:
      - "${VITE_PORT_EXPORT_REACT:-5173}:${VITE_PORT_DEFAULT_REACT:-5173}"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL:-https://farmacia-nest.onrender.com/}

volumes:
  node_modules:
